item1=input("Enter the name of the item1 : ")
price1=int(input("Enter the price of item1 : "))
q1=int(input("Enter the quantity of item1: "))
item2=input("Enter the name of the item2 : ")
price2=int(input("Enter the price of item2 : "))
q2=int(input("Enter the quantity of item2: "))
item3=input("Enter the name of the item3 : ")
price3=int(input("Enter the price of item3 : "))
q3=int(input("Enter the quantity of item3: "))
sum=(price1*q1)+(price2*q2)+(price3*q3)
print(sum)